# Use root/example as user/password credentials
version: '3.1'

services:
  transmission-bt:
    image: linuxserver/transmission
    restart: always
    ports: 
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    environment:
      TZ: America/New_York
      PUID: 117
      PGID: 126
    volumes:
      - ./config:/config
      - ./downloads:/downloads
      # - ./watch:/watch
